"""add description to roles

Revision ID: ebe686c23962
Revises: 4a5b6c7d8e9f
Create Date: 2026-06-18 18:26:22.383764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe686c23962'
down_revision: Union[str, Sequence[str], None] = '4a5b6c7d8e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('comentarios_tarea_autor_id_fkey'), 'comentarios_tarea', type_='foreignkey')
    op.create_foreign_key(None, 'comentarios_tarea', 'users', ['autor_id'], ['id'])
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('tareas_asignado_por_fkey'), 'tareas', type_='foreignkey')
    op.create_foreign_key(None, 'tareas', 'users', ['asignado_por'], ['id'])
    op.alter_column('usuarios', 'cbu',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('uix_versiones_padron_activa'), table_name='versiones_padron', postgresql_where='(activa = true)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uix_versiones_padron_activa'), 'versiones_padron', ['tenant_id', 'materia_id', 'cohorte_id'], unique=True, postgresql_where='(activa = true)')
    op.alter_column('usuarios', 'cbu',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'tareas', type_='foreignkey')
    op.create_foreign_key(op.f('tareas_asignado_por_fkey'), 'tareas', 'usuarios', ['asignado_por'], ['id'])
    op.drop_column('roles', 'description')
    op.drop_constraint(None, 'comentarios_tarea', type_='foreignkey')
    op.create_foreign_key(op.f('comentarios_tarea_autor_id_fkey'), 'comentarios_tarea', 'usuarios', ['autor_id'], ['id'])
    # ### end Alembic commands ###
